title: Md. Abu Sayed
#logo: /assets/img/headshot_circle.png
description: Proficient in model implementation, data manipulation, and visualization. Skilled in machine learning techniques and software engineering. Currently seeking opportunities in the field of data science and machine learning to contribute to impactful research and innovative projects.
#show_downloads: False
remote_theme: pages-themes/modernist@v0.2.0
